import type { SignalLeadMapLead } from "../contracts";

/**
 * Placeholder matched leads shown when the backend mapping is empty (e.g. the
 * org has no leads uploaded yet), so "Find Matched Leads" still demonstrates the
 * flow. Deterministic per signal id — remove once real leads are synced.
 */
const DEMO_POOL: Omit<SignalLeadMapLead, "lead_id">[] = [
  {
    name: "Rohit Khanna",
    title: "VP Engineering",
    seniority: "VP",
    email: "rohit@northwind.ai",
    email_status: "verified",
    linkedin: "https://www.linkedin.com/in/rohit-khanna",
    phone: "",
    company: "Northwind Analytics",
    relevance: "high",
    why: "Series B SaaS scaling GTM in EMEA — matches the signal's ICP profile.",
  },
  {
    name: "Navneet Yadav",
    title: "CPO",
    seniority: "C-Level",
    email: "navneet@kestrelcloud.com",
    email_status: "verified",
    linkedin: "https://www.linkedin.com/in/navneet-yadav",
    phone: "",
    company: "Kestrel Cloud",
    relevance: "high",
    why: "Recently posted 12 sales roles, indicating active pipeline expansion.",
  },
  {
    name: "Corey Stein",
    title: "SVP Engineering",
    seniority: "SVP",
    email: "corey@lumenretail.com",
    email_status: "guessed",
    linkedin: "https://www.linkedin.com/in/corey-stein",
    phone: "",
    company: "Lumen Retail Group",
    relevance: "medium",
    why: "Mid-market buyer with adjacent use case; needs qualification.",
  },
  {
    name: "Michael Greer",
    title: "Head of Operations",
    seniority: "Head",
    email: "michael@brightpath.io",
    email_status: "verified",
    linkedin: "https://www.linkedin.com/in/michael-greer",
    phone: "",
    company: "Brightpath Logistics",
    relevance: "medium",
    why: "Operates in a target vertical but revenue stage is unconfirmed.",
  },
  {
    name: "Sophie Roberts",
    title: "CTO",
    seniority: "C-Level",
    email: "sophie@velahealth.com",
    email_status: "unverified",
    linkedin: "https://www.linkedin.com/in/sophie-roberts",
    phone: "",
    company: "Vela Health",
    relevance: "low",
    why: "Peripheral fit — monitor for a stronger trigger before outreach.",
  },
  {
    name: "Aisha Rahman",
    title: "Director of Revenue Operations",
    seniority: "Director",
    email: "aisha@meridianpay.com",
    email_status: "verified",
    linkedin: "https://www.linkedin.com/in/aisha-rahman",
    phone: "",
    company: "Meridian Pay",
    relevance: "high",
    why: "RevOps owner at a fintech consolidating its GTM stack this quarter.",
  },
  {
    name: "Daniel Okafor",
    title: "Head of Growth",
    seniority: "Head",
    email: "daniel@arborworks.io",
    email_status: "verified",
    linkedin: "https://www.linkedin.com/in/daniel-okafor",
    phone: "",
    company: "Arborworks",
    relevance: "high",
    why: "Doubled headcount post-Series A — buying committee is forming now.",
  },
  {
    name: "Elena Vasquez",
    title: "VP Marketing",
    seniority: "VP",
    email: "elena@solstice-crm.com",
    email_status: "guessed",
    linkedin: "https://www.linkedin.com/in/elena-vasquez",
    phone: "",
    company: "Solstice CRM",
    relevance: "medium",
    why: "Owns demand-gen budget; competing priorities may delay evaluation.",
  },
  {
    name: "Marcus Feld",
    title: "Chief Revenue Officer",
    seniority: "C-Level",
    email: "marcus@hallmarkindustrial.com",
    email_status: "verified",
    linkedin: "https://www.linkedin.com/in/marcus-feld",
    phone: "",
    company: "Hallmark Industrial",
    relevance: "medium",
    why: "Enterprise account with a long cycle but strong strategic fit.",
  },
  {
    name: "Priya Iyer",
    title: "Sales Operations Manager",
    seniority: "Manager",
    email: "priya@northgate-labs.com",
    email_status: "unverified",
    linkedin: "https://www.linkedin.com/in/priya-iyer",
    phone: "",
    company: "Northgate Labs",
    relevance: "low",
    why: "Influencer rather than decision maker — useful for internal referral.",
  },
  {
    name: "James Chen",
    title: "VP Sales",
    seniority: "VP",
    email: "james@vertexdata.io",
    email_status: "verified",
    linkedin: "https://www.linkedin.com/in/james-chen",
    phone: "",
    company: "Vertex Data",
    relevance: "high",
    why: "Leading a 40-person sales org replatforming its outbound stack this quarter.",
  },
  {
    name: "Linda O'Brien",
    title: "Chief Technology Officer",
    seniority: "C-Level",
    email: "linda@pillarhealth.com",
    email_status: "verified",
    linkedin: "https://www.linkedin.com/in/linda-obrien",
    phone: "",
    company: "Pillar Health",
    relevance: "high",
    why: "New CTO mandate to consolidate data vendors after a recent acquisition.",
  },
  {
    name: "Arjun Mehta",
    title: "Director of Business Development",
    seniority: "Director",
    email: "arjun@orbitlogistics.ai",
    email_status: "guessed",
    linkedin: "https://www.linkedin.com/in/arjun-mehta",
    phone: "",
    company: "Orbit Logistics",
    relevance: "medium",
    why: "Expanding partner channel; evaluating enablement tools for reseller onboarding.",
  },
  {
    name: "Sarah Kim",
    title: "Head of Customer Success",
    seniority: "Head",
    email: "sarah@nexuscomply.com",
    email_status: "verified",
    linkedin: "https://www.linkedin.com/in/sarah-kim",
    phone: "",
    company: "Nexus Comply",
    relevance: "medium",
    why: "Scaling CS ops and looking for automation to reduce onboarding time.",
  },
  {
    name: "David Patel",
    title: "VP Engineering",
    seniority: "VP",
    email: "david@quantumretail.co",
    email_status: "verified",
    linkedin: "https://www.linkedin.com/in/david-patel",
    phone: "",
    company: "Quantum Retail",
    relevance: "high",
    why: "Modernising inventory systems; active RFP for predictive analytics vendors.",
  },
  {
    name: "Emily Zhang",
    title: "Senior Product Manager",
    seniority: "Manager",
    email: "emily@fincraft.io",
    email_status: "unverified",
    linkedin: "https://www.linkedin.com/in/emily-zhang",
    phone: "",
    company: "Fincraft",
    relevance: "low",
    why: "Right vertical but individual contributor without budget authority.",
  },
  {
    name: "Omar Hassan",
    title: "CEO",
    seniority: "C-Level",
    email: "omar@trellisfarms.com",
    email_status: "verified",
    linkedin: "https://www.linkedin.com/in/omar-hassan",
    phone: "",
    company: "Trellis Farms",
    relevance: "medium",
    why: "Founder-led buyer exploring operational efficiency tools for the next funding round.",
  },
  {
    name: "Rachel Green",
    title: "VP Marketing",
    seniority: "VP",
    email: "rachel@streamlinehq.com",
    email_status: "guessed",
    linkedin: "https://www.linkedin.com/in/rachel-green",
    phone: "",
    company: "Streamline HQ",
    relevance: "high",
    why: "Doubled marketing spend; needs attribution and lead-routing infrastructure.",
  },
  {
    name: "Tom Bradley",
    title: "Director of IT",
    seniority: "Director",
    email: "tom@axismanufacturing.com",
    email_status: "verified",
    linkedin: "https://www.linkedin.com/in/tom-bradley",
    phone: "",
    company: "Axis Manufacturing",
    relevance: "medium",
    why: "Evaluating new vendor stack after legacy contract expires next quarter.",
  },
  {
    name: "Nina Kowalski",
    title: "Chief Operating Officer",
    seniority: "C-Level",
    email: "nina@forgeenergy.io",
    email_status: "verified",
    linkedin: "https://www.linkedin.com/in/nina-kowalski",
    phone: "",
    company: "Forge Energy",
    relevance: "high",
    why: "Operations leader driving cost-reduction initiative across distributed teams.",
  },
  {
    name: "Daniel Okafor",
    title: "Director of Revenue Operations",
    seniority: "Director",
    email: "daniel@vantagehealth.com",
    email_status: "verified",
    linkedin: "https://www.linkedin.com/in/daniel-okafor",
    phone: "",
    company: "Vantage Health",
    relevance: "high",
    why: "Owns the RevOps tooling budget and is consolidating vendors this quarter.",
  },
  {
    name: "Priya Ramanathan",
    title: "Head of Growth",
    seniority: "Head",
    email: "priya@saffronpay.com",
    email_status: "verified",
    linkedin: "https://www.linkedin.com/in/priya-ramanathan",
    phone: "",
    company: "SaffronPay",
    relevance: "high",
    why: "Fintech scaling into new markets — the signal maps directly to her expansion plan.",
  },
  {
    name: "Lukas Berger",
    title: "VP Sales",
    seniority: "VP",
    email: "lukas@helvetiaworks.ch",
    email_status: "guessed",
    linkedin: "https://www.linkedin.com/in/lukas-berger",
    phone: "",
    company: "Helvetia Works",
    relevance: "medium",
    why: "Fits firmographics but no recent buying trigger observed.",
  },
  {
    name: "Amara Ndiaye",
    title: "Chief Data Officer",
    seniority: "C-Level",
    email: "amara@meridianbank.com",
    email_status: "verified",
    linkedin: "https://www.linkedin.com/in/amara-ndiaye",
    phone: "",
    company: "Meridian Bank",
    relevance: "high",
    why: "Regulated buyer under pressure to modernise reporting — high urgency fit.",
  },
  {
    name: "Tomás Herrera",
    title: "Head of Procurement",
    seniority: "Head",
    email: "tomas@andesfoods.mx",
    email_status: "guessed",
    linkedin: "https://www.linkedin.com/in/tomas-herrera",
    phone: "",
    company: "Andes Foods",
    relevance: "low",
    why: "Gatekeeper contact only; economic buyer not yet identified.",
  },
  {
    name: "Hannah Whitfield",
    title: "Director of IT",
    seniority: "Director",
    email: "hannah@claridgeretail.co.uk",
    email_status: "verified",
    linkedin: "https://www.linkedin.com/in/hannah-whitfield",
    phone: "",
    company: "Claridge Retail",
    relevance: "medium",
    why: "Renewal window opens in two quarters; worth nurturing now.",
  },
  {
    name: "Kenji Watanabe",
    title: "General Manager, Digital",
    seniority: "GM",
    email: "kenji@sakuramobility.jp",
    email_status: "verified",
    linkedin: "https://www.linkedin.com/in/kenji-watanabe",
    phone: "",
    company: "Sakura Mobility",
    relevance: "medium",
    why: "Running a digital transformation programme adjacent to the signal's theme.",
  },
  {
    name: "Elena Rossi",
    title: "VP Customer Success",
    seniority: "VP",
    email: "elena@borealissoft.eu",
    email_status: "guessed",
    linkedin: "https://www.linkedin.com/in/elena-rossi",
    phone: "",
    company: "Borealis Software",
    relevance: "low",
    why: "Influencer rather than buyer; useful for a warm internal referral.",
  },
  {
    name: "Diego Marín",
    title: "VP Sales",
    seniority: "VP",
    email: "diego@velacargo.io",
    email_status: "verified",
    linkedin: "https://www.linkedin.com/in/diego-marin",
    phone: "",
    company: "Vela Cargo",
    relevance: "high",
    why: "Just closed Series C and tripled the sales team — green-lighting GTM tooling now.",
  },
  {
    name: "Meera Joshi",
    title: "Head of RevOps",
    seniority: "Head",
    email: "meera@quantedge.co",
    email_status: "verified",
    linkedin: "https://www.linkedin.com/in/meera-joshi",
    phone: "",
    company: "Quantedge",
    relevance: "high",
    why: "Consolidating five sales tools into one stack this quarter — actively evaluating vendors.",
  },
  {
    name: "Lucas Brandt",
    title: "Director of Sales",
    seniority: "Director",
    email: "lucas@helixbiotech.com",
    email_status: "guessed",
    linkedin: "https://www.linkedin.com/in/lucas-brandt",
    phone: "",
    company: "Helix Biotech",
    relevance: "medium",
    why: "Hiring across SDR and AE roles; tooling budget expected to open next quarter.",
  },
  {
    name: "Fatima Al-Sayed",
    title: "Chief Commercial Officer",
    seniority: "C-Level",
    email: "fatima@meridianlogistics.ae",
    email_status: "verified",
    linkedin: "https://www.linkedin.com/in/fatima-alsayed",
    phone: "",
    company: "Meridian Logistics",
    relevance: "high",
    why: "Spearheading a regional expansion and needs an outbound engine to support it.",
  },
  {
    name: "Ben Carver",
    title: "VP Marketing",
    seniority: "VP",
    email: "ben@northbeam.io",
    email_status: "guessed",
    linkedin: "https://www.linkedin.com/in/ben-carver",
    phone: "",
    company: "Northbeam",
    relevance: "medium",
    why: "Demand-gen owner scaling paid channels; evaluating attribution + routing tools.",
  },
  {
    name: "Yuki Tanaka",
    title: "Head of Partnerships",
    seniority: "Head",
    email: "yuki@asahitech.jp",
    email_status: "verified",
    linkedin: "https://www.linkedin.com/in/yuki-tanaka",
    phone: "",
    company: "Asahi Tech",
    relevance: "medium",
    why: "Building a reseller programme; evaluating enablement platforms for partner onboarding.",
  },
  {
    name: "Olivia Park",
    title: "Director of Growth",
    seniority: "Director",
    email: "olivia@fintura.io",
    email_status: "verified",
    linkedin: "https://www.linkedin.com/in/olivia-park",
    phone: "",
    company: "Fintura",
    relevance: "high",
    why: "Leading a PLG-to-sales motion and needs a structured outbound pipeline immediately.",
  },
  {
    name: "Ravi Menon",
    title: "CFO",
    seniority: "C-Level",
    email: "ravi@vectorind.com",
    email_status: "verified",
    linkedin: "https://www.linkedin.com/in/ravi-menon",
    phone: "",
    company: "Vector Industries",
    relevance: "low",
    why: "Economic buyer but not an outbound champion — route through his RevOps lead instead.",
  },
  {
    name: "Sofia Nilsson",
    title: "VP Customer Success",
    seniority: "VP",
    email: "sofia@nordson.se",
    email_status: "guessed",
    linkedin: "https://www.linkedin.com/in/sofia-nilsson",
    phone: "",
    company: "Nordson",
    relevance: "medium",
    why: "Churn-reduction initiative underway; evaluating CS tooling that overlaps with the signal.",
  },
  {
    name: "Andre Costa",
    title: "Head of Sales",
    seniority: "Head",
    email: "andre@pluvia.com.br",
    email_status: "verified",
    linkedin: "https://www.linkedin.com/in/andre-costa",
    phone: "",
    company: "Pluvia",
    relevance: "high",
    why: "Replatforming the entire sales stack after legacy CRM contract expires in 60 days.",
  },
  {
    name: "Hannah Brooks",
    title: "Senior Director, GTM",
    seniority: "Director",
    email: "hannah@corvusdata.ai",
    email_status: "verified",
    linkedin: "https://www.linkedin.com/in/hannah-brooks",
    phone: "",
    company: "Corvus Data",
    relevance: "high",
    why: "Recently hired to stand up outbound — no incumbent vendor, clear greenfield fit.",
  },
];

export function getDemoMatchedLeads(signalId: string): SignalLeadMapLead[] {
  const seed = Array.from(signalId).reduce((n, c) => n + c.charCodeAt(0), 0);
  const count = 14 + (seed % 6); // 14–19 leads
  return Array.from({ length: count }, (_, i) => {
    const base = DEMO_POOL[(seed + i) % DEMO_POOL.length];
    return { ...base, lead_id: `demo-${signalId}-${i}` };
  });
}

/**
 * Real mapped leads plus deterministic demo rows so "Find Matched Leads" always
 * shows a populated table while the org's lead data is still thin.
 */
export function withDemoMatchedLeads(
  signalId: string,
  real: SignalLeadMapLead[],
  minimum = 10,
): SignalLeadMapLead[] {
  if (real.length >= minimum) return real;
  const filler = getDemoMatchedLeads(signalId).filter(
    (demo) => !real.some((r) => r.name === demo.name && r.company === demo.company),
  );
  return [...real, ...filler].slice(0, Math.max(minimum, real.length));
}
