import { jsPDF } from "jspdf";

import type { ArtefactItem } from "../types";

// jsPDF owns PDF string encoding, so structural ( ) \ escaping is no longer
// needed. We keep ASCII-folding as a WinAnsi safety net: jsPDF's default
// Helvetica still mojibakes em/en dashes, smart quotes and bullets. (Residual
// non-ASCII such as accented names remains an accepted limitation — the
// Unicode-font-embedding half of TD-FE-78 stays open; no font is embedded here.)
export const escapePdfText = (input: string): string =>
  (input ?? "")
    .replace(/[–—]/g, "-")
    .replace(/['']/g, "'")
    .replace(/[“”]/g, '"')
    .replace(/•/g, "-");

const MARGIN = 50;

/** Build a structurally valid, wrapped + paginated PDF for an ArtefactItem. */
export const buildArtefactPdfDoc = (artefact: ArtefactItem): jsPDF => {
  const doc = new jsPDF({ unit: "pt", format: "letter" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const maxWidth = pageWidth - MARGIN * 2;
  let y = MARGIN;

  const lineHeight = () => doc.getLineHeight() / doc.internal.scaleFactor;
  const ensureSpace = () => {
    if (y + lineHeight() > pageHeight - MARGIN) {
      doc.addPage();
      y = MARGIN;
    }
  };
  const writeBlock = (text: string, fontSize: number, bold: boolean) => {
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.setFontSize(fontSize);
    const lines = doc.splitTextToSize(escapePdfText(text || ""), maxWidth) as string[];
    for (const line of lines) {
      ensureSpace();
      doc.text(line, MARGIN, y);
      y += lineHeight();
    }
  };
  const gap = (pts: number) => {
    y += pts;
  };

  const { fullReport } = artefact;
  writeBlock(fullReport.title, 18, true);
  gap(4);
  writeBlock(
    `Generated by: ${artefact.agentName} | ${artefact.timestamp} | Task ID: ${artefact.taskNumber}`,
    9,
    false,
  );
  gap(12);

  writeBlock("EXECUTIVE SUMMARY", 13, true);
  writeBlock(fullReport.executiveSummary, 10, false);
  gap(10);

  writeBlock("KEY FINDINGS", 13, true);
  fullReport.keyFindings.forEach((f, i) => writeBlock(`${i + 1}. ${f}`, 10, false));
  gap(10);

  writeBlock("ANALYSIS", 13, true);
  writeBlock(fullReport.analysis, 10, false);
  gap(10);

  writeBlock("RECOMMENDATIONS", 13, true);
  fullReport.recommendations.forEach((r, i) => writeBlock(`${i + 1}. ${r}`, 10, false));
  gap(16);

  writeBlock(`Generated by Brewra AI • ${new Date().toLocaleDateString()}`, 8, false);

  return doc;
};

export const buildArtefactPdfBlob = (artefact: ArtefactItem): Blob =>
  buildArtefactPdfDoc(artefact).output("blob");

export const generateAndDownloadPDF = (artefact: ArtefactItem): void => {
  const blob = buildArtefactPdfBlob(artefact);
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  const slug = artefact.fullReport.title.replace(/[^a-z0-9]/gi, "_").toLowerCase();
  // Short uniquifier so re-saving the same artefact doesn't overwrite the prior file.
  link.download = `${slug}-${Date.now()}.pdf`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};
