import type { ArtefactItem } from "../types";

export const createSimplePDF = (artefact: ArtefactItem): string => {
  // Create a minimal PDF structure
  const title = artefact.fullReport.title;
  const agentName = artefact.agentName;
  const timestamp = artefact.timestamp;
  const taskId = artefact.taskNumber;
  const executiveSummary = artefact.fullReport.executiveSummary;
  const keyFindings = artefact.fullReport.keyFindings;
  const analysis = artefact.fullReport.analysis;
  const recommendations = artefact.fullReport.recommendations;
  const date = new Date().toLocaleDateString();

  // Simple PDF content structure
  const pdfData = `%PDF-1.4
1 0 obj
<<
/Type /Catalog
/Pages 2 0 R
>>
endobj

2 0 obj
<<
/Type /Pages
/Kids [3 0 R]
/Count 1
>>
endobj

3 0 obj
<<
/Type /Page
/Parent 2 0 R
/MediaBox [0 0 612 792]
/Contents 4 0 R
/Resources <<
/Font <<
/F1 5 0 R
/F2 6 0 R
>>
>>
>>
endobj

4 0 obj
<<
/Length 2000
>>
stream
BT
/F1 16 Tf
50 750 Td
(${title}) Tj
0 -30 Td
/F2 10 Tf
(Generated by: ${agentName} | ${timestamp} | Task ID: ${taskId}) Tj
0 -40 Td
/F1 14 Tf
(EXECUTIVE SUMMARY) Tj
0 -20 Td
/F2 10 Tf
(${executiveSummary}) Tj
0 -40 Td
/F1 14 Tf
(KEY FINDINGS) Tj
0 -20 Td
/F2 10 Tf
${keyFindings.map((finding, index) => `(${index + 1}. ${finding}) Tj 0 -15 Td`).join("\n")}
0 -20 Td
/F1 14 Tf
(ANALYSIS) Tj
0 -20 Td
/F2 10 Tf
(${analysis}) Tj
0 -40 Td
/F1 14 Tf
(RECOMMENDATIONS) Tj
0 -20 Td
/F2 10 Tf
${recommendations.map((rec, index) => `(${index + 1}. ${rec}) Tj 0 -15 Td`).join("\n")}
0 -40 Td
/F2 8 Tf
(Generated by Brewra AI • ${date}) Tj
ET
endstream
endobj

5 0 obj
<<
/Type /Font
/Subtype /Type1
/BaseFont /Helvetica-Bold
>>
endobj

6 0 obj
<<
/Type /Font
/Subtype /Type1
/BaseFont /Helvetica
>>
endobj

xref
0 7
0000000000 65535 f 
0000000009 00000 n 
0000000058 00000 n 
0000000115 00000 n 
0000000274 00000 n 
0000002000 00000 n 
0000002500 00000 n 
trailer
<<
/Size 7
/Root 1 0 R
>>
startxref
3000
%%EOF`;

  return pdfData;
};

export const generateAndDownloadPDF = (artefact: ArtefactItem): void => {
  // Create a simple PDF using jsPDF-like approach
  const pdfContent = createSimplePDF(artefact);

  // Create a blob with PDF content
  const blob = new Blob([pdfContent], { type: "application/pdf" });
  const url = URL.createObjectURL(blob);

  // Create a temporary link element and trigger download
  const link = document.createElement("a");
  link.href = url;
  link.download = `${artefact.fullReport.title.replace(/[^a-z0-9]/gi, "_").toLowerCase()}.pdf`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  // Clean up the URL object
  URL.revokeObjectURL(url);
};
